### PR TITLE
Migration to TronWeb 2

### PR DESCRIPTION
**Pull request by sullof**
I have migrated tronbox from tronweb1 to tronweb2.
Right now:
`migrate` works.
`unbox` works recovering the data from the new box repos (see below)
`test` is still not working.

The new boxes:
tronbox init (https://github.com/sullof/bare-box)
tronbox unbox metacoin (https://github.com/sullof/metacoin-box)
As soon as possible @tronprotocol should fork them and use the official namespace for them.

For clarity, I have removed from the monorepo any truffle package which has not been modified for tronbox. This way Lerna loads them from the npm registry. If in the future we need to customize some of them, we can re-add them in the monorepo.

To simplify the development, I have added https://github.com/tronprotocol/tron-web as a submodule of the package TronWrap, which is the wrapper around TronWeb that is actually used by the commands.
To avoid that someone by mistake pushes a branch of TronWeb which is not master, I added a pre-push hook in git. In this branch, right now, I am loading the branch 

Finally, I have set better copyright info in package.json. Also, I have renamed the primary packages from truffle to tronbox.

TO BE CONTINUED...

### CODE REVIEW

**Comment by sullof** [comment]
After many attempts, I figured out why tests were not working.
Still, tests written in Solidity don't work, but I hope I can fix it soon.

**Comment by sullof** [comment]
Last commit restore the old format during tests, where `Contract.deployed().call('method',...)` returns an array, while instead TronWeb 2, if the array has only one element, instead of returning the array, returns the element.
The reverse is done in TronWrap, without changing TronWeb.
In the future, we can change the policy. For now this allows people to test easily their code without changing anything, if they used the `.call` method in the tests, like in https://github.com/sullof/metacoin-box/blob/master/test/metacoin.js

**Comment by sullof** [comment]
Based on https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html 

> If it returns a single value, it’s returned as is. If it has multiple return values they are returned as an object with properties and indices

I did that change to try to reduce as much as possible the changes developer have to do to port a truffle project to tronbox. But I am fine with the idea of forcing our developers to move towards a Web3 1.0 approach. In this case, though, I would add a few more changes to TronWeb, starting from let `myMethod(...).call()` return an object instead of an array. 
Also, for example, we could keep but deprecate
```
contract.new(...)
```
in favor of 
```
new tronweb.trx.contract(...)
```

**Comment by sullof** [comment]
I didn't check. If it already returns an object, we are good :-)

About the contract class, we could just add a class wrapping the existent contract.new(), keeping the former for retro-compatibility. 
In general, I am against changes that break working things. 
But since we are already forcing developers to change that because they cannot call anymore a contract method as before, maybe it is better to set a strong break and go forward to the new approach suggesting whoever wants to keep the old approach to install old versions of tronbox and tronweb.

My feeling is that we can make TronWeb work like Web3 0.x or like Web3 1.0, what I would avoid is to mix the concepts because it's very confusing for any developers who also works with Ethereum.
Of course, I leave the decision to @kookiekrak and for now I am porting TronBox fully respecting TronWeb 2 (except the last PR, that I can easily reverse).

**Comment by Kondax** [comment]
Completely agree.

**Comment by sullof** [comment]
@kookiekrak @Kondax 
Everything seems to work well.

To be consistent with TronWeb, I reversed the PR where I was converting `result` to `[result]`, and pushed an updated version of Metacoin-box at https://github.com/sullof/metacoin-box.

Before merging this PR to master, it is important that we decide if we prefer to change something in TronWeb. And I think it would be better to extend the conversation to other people since this has repercussions on community management, documentation, etc.

**Comment by sullof** [comment]
About the packages that have been modified in the tool, I think that it would be better to rename them, specifying in the README that it is a fork of the respecting Truffle package. WDYT?

**Comment by sullof** [comment]
The tests don't work. But are not working even in master. I will fix them in a future PR.

**Comment by Kondax** [comment]
Gotcha. I think this should have more input, but at the moment we're the only two people who have worked on TronWeb.

**Comment by sullof** [comment]
Just to be clear, I was talking about the tests about Tronbox itself, which don't work.
Instead, the tests in an app, like the MetaCoin example, work perfectly.

**Comment by kookiekrak** [comment]
lets get everything working for now. 

we can do a breaking version in the future where we cut over to web3 1.x syntax.

or we can just support both 0.x and 1.x for maximum compatibility with all types.

**Pull request merged**
